title: "Ryan Harrison"

tagline: "My blog, portfolio and technology related ramblings"

avatar: "/images/avatar.png"

footer-links:
  github: raharrison
  linkedin: ryanharrison10
  rss: rss
  twitter: ryanalready

disqus: ryanharrison
google_analytics: G-9MVP1BEKQY

# Used by sitemap.xml and the RSS feed
url: https://ryanharrison.co.uk
baseurl: ''

paginate: 5

collections:
  pages:
    output: true
    permalink: /:name

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate # Pagination of posts

# Post excerpts include everything up to this tag
excerpt_separator: <!--more-->

# Custom vars
version: 1.2.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # Or use :expanded

# Exclude these files from the production _site
exclude:
    - .idea
    - debug.log
    - utils
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - LICENSE.md
    - README.md
    - CLAUDE.md
    - docker-compose.yml
    - CNAME